# rpf JAVAC_FLAGS = -target 1.5
# turn off targeet 1.5 flag
JAVAC_FLAGS = 

COMPILE = javac $(JAVAC_FLAGS) $?

all: BaseBasecaller.class FakeFile.class GenotypeData.class GenotypeLauncher.class GenotypeParser.class GenotypeTrace.class GenotypeViewer.class GenotypeViewerCredits.class GZIPOpen.class JGenotypeViewer.class JGenotypeViewerCredits.class JTraceCanvas.class JTracePanel.class JTraceViewer.class MTV.class MultiScrollPanel.class MultiTraceViewer.class PhdData.class PhdFile.class Poly.class PolyData.class PolyFile.class PolyPeak.class RandomAccessStream.class RSRandomAccessFile.class StreamDelegator.class TraceCanvas.class TraceDataView.class TraceFile.class TraceLauncher.class TraceLoader.class TracePanel.class TraceServer.class TraceServerClient.class TraceViewer.class TraceZoomer.class 

BaseBasecaller.class: BaseBasecaller.java
	$(COMPILE)

FakeFile.class: FakeFile.java
	$(COMPILE)

GenotypeData.class: GenotypeData.java
	$(COMPILE)

GenotypeLauncher.class: GenotypeLauncher.java
	$(COMPILE)

GenotypeParser.class: GenotypeParser.java
	$(COMPILE)

GenotypeTrace.class: GenotypeTrace.java
	$(COMPILE)

GenotypeViewer.class: GenotypeViewer.java
	$(COMPILE)

GenotypeViewerCredits.class: GenotypeViewerCredits.java
	$(COMPILE)

GZIPOpen.class: GZIPOpen.java
	$(COMPILE)

JGenotypeViewer.class: JGenotypeViewer.java
	$(COMPILE)

JGenotypeViewerCredits.class: JGenotypeViewerCredits.java
	$(COMPILE)

JTraceCanvas.class: JTraceCanvas.java
	$(COMPILE)

JTracePanel.class: JTracePanel.java
	$(COMPILE)

JTraceViewer.class: JTraceViewer.java
	$(COMPILE)

MTV.class: MTV.java
	$(COMPILE)

MultiScrollPanel.class: MultiScrollPanel.java
	$(COMPILE)

MultiTraceViewer.class: MultiTraceViewer.java
	$(COMPILE)

PhdData.class: PhdData.java
	$(COMPILE)

PhdFile.class: PhdFile.java
	$(COMPILE)

Poly.class: Poly.java
	$(COMPILE)

PolyData.class: PolyData.java
	$(COMPILE)

PolyFile.class: PolyFile.java
	$(COMPILE)

PolyPeak.class: PolyPeak.java
	$(COMPILE)

RandomAccessStream.class: RandomAccessStream.java
	$(COMPILE)

RSRandomAccessFile.class: RSRandomAccessFile.java
	$(COMPILE)

StreamDelegator.class: StreamDelegator.java
	$(COMPILE)

TraceCanvas.class: TraceCanvas.java
	$(COMPILE)

TraceDataView.class: TraceDataView.java
	$(COMPILE)

TraceFile.class: TraceFile.java
	$(COMPILE)

TraceLauncher.class: TraceLauncher.java
	$(COMPILE)

TraceLoader.class: TraceLoader.java
	$(COMPILE)

TracePanel.class: TracePanel.java
	$(COMPILE)

TraceServer.class: TraceServer.java
	$(COMPILE)

TraceServerClient.class: TraceServerClient.java
	$(COMPILE)

TraceViewer.class: TraceViewer.java
	$(COMPILE)

TraceZoomer.class: TraceZoomer.java
	$(COMPILE)

clean: 
	rm -f  *.class 

